### ISSUE TITLE
Same message consumed 10 times

### ISSUE THREAD

**Issue by sevagh** [koding/rabbitmq#2]
Hello,

I'm trying to run something similar to your example code, and every message I produce is consumed exactly 10 times.

Is there a consumer setting I need to set?

Postgresql message store:

rabbitmq=# select \* from messages;
 id | producer_id | body  |         timestamp  
----+-------------+-------+----------------------------
  1 |        1234 | hello | 2016-03-27 12:42:28.584506
  2 |        1234 | hello | 2016-03-27 12:42:28.587282
  3 |        1234 | hello | 2016-03-27 12:42:28.588252
  4 |        1234 | hello | 2016-03-27 12:42:28.589166
  5 |        1234 | hello | 2016-03-27 12:42:28.590046
  6 |        1234 | hello | 2016-03-27 12:42:28.59098
  7 |        1234 | hello | 2016-03-27 12:42:28.591891
  8 |        1234 | hello | 2016-03-27 12:42:28.592841
  9 |        1234 | hello | 2016-03-27 12:42:28.593765
 10 |        1234 | hello | 2016-03-27 12:42:28.594651

**Comment by sevagh** [comment]
Its related to the default QOS = 10, right? My handler is:

```
{
   //push message to postgres
   //ack
 }
```

This loop is running 10 times. Should I manually check if a message has been acked or what?

**Comment by cihangir** [comment]
Hey @sevagh is it possible that you are publishing the same message 10 times like we demonstrate here? https://github.com/koding/rabbitmq/blob/master/examples/producer.go#L49 

Otherwise it is not possible to consume the same message if you `Ack` it at the end of your operation due to RMQ. We are running the same code in production for years without a problem. Feel free to reopen if you find any kind of bug in our package.

**Comment by sevagh** [comment]
Oops, I totally tunnel-visioned on the consumer and didn't realize there was a loop in the producer. Thanks.
